echo "% Autogenerated, do not edit" > revision.tex
echo "\\newcommand{\\revisiondate}{`git log -1 --format=\"%ad\" --date=short`}" >> revision.tex
echo "\\newcommand{\\revision}{`git log -1 --format=\"%h\"`}" >> revision.tex
